'''
Luke Katsel
Week 9 
10/23/23
'''

'''
Using the pypcapfile library (already available in the VLE),  along with the sample PCAP Files provided, develop a Python Script that extracts features of each packet. 

For each processed PCAP File generate a report with the following information for each unique connection observed and each Observed Port.

Sample Output Files are included for your review.

Submit the following:

1) Your python script

2) The report generated by your script that demonstrates the processing of each PCAP File provided.

'''

'''

WK-9 PCAP SOLUTION SCRIPT

Written exclusively for Python 3.4.x or above

Overview:

The script ingests a standard PCAP File and creates a passive
asset map based on the observed UNIQUE activity and stores the
resultng map as a serialzed python object.  In addition, an html
file is generated that depicts the observed asset map.
'''
# Python Standard Library Module Imports

import sys               # System specifics
import platform          # Platform specifics
import os                # Operating/Filesystem Module
import pickle            # Object serialization
import time              # Basic Time Module
import re                # regular expression library
from binascii import unhexlify

# 3rd Party Libraries

from prettytable import PrettyTable   # pip install prettytable

'''
Simple PCAP File 3rd Party Library 
to process pcap file contents 

To install the Library
pip install pypcapfile 

'''

from pcapfile import savefile
from pcapfile.protocols.linklayer import ethernet
from pcapfile.protocols.network   import ip
from pcapfile.protocols.transport import tcp
from pcapfile.protocols.transport import udp


# Script Constants

NAME    = "PYTHON PCAP PROCESSOR"
VERSION = "VERSION 1.0 AUGUST 2021"
DEBUG   = True

# Script Constants

DEBUG = True

# Script Local Functions


class ETH:
    '''LOOKUP ETH TYPE'''
    def __init__(self):
    
        self.ethTypes = {}
        
        self.ethTypes[2048]   = "IPv4"
        self.ethTypes[2054]   = "ARP"
        self.ethTypes[34525]  = "IPv6"
            
    def lookup(self, ethType):
        
        try:
            result = self.ethTypes[ethType]
        except:
            result = "not-supported"
            
        return result

# MAC Address Lookup Class
class MAC:
    ''' OUI TRANSLATION MAC TO MFG'''
    def __init__(self):
        
        # Open the MAC Address OUI Dictionary
        with open('oui.pickle', 'rb') as pickleFile:
            self.macDict = pickle.load(pickleFile)
            
    def lookup(self, macAddress):
        try:
            result = self.macDict[macAddress]
            cc  = result[0]
            oui = result[1]
            return cc+","+oui
        except:
            return "Unknown"
        
# Transport Lookup Class

class TRANSPORT:
    ''' PROTOCOL TO NAME LOOKUP'''
    def __init__(self):
        
        # Open the transport protocol Address OUI Dictionary
        with open('protocol.pickle', 'rb') as pickleFile:
            self.proDict = pickle.load(pickleFile)
    def lookup(self, protocol):
        try:
            result = self.proDict[protocol]
            return result
        except:
            return ["unknown", "unknown", "unknown"]

#PORTS Lookup Class

class PORTS:
    ''' PORT NUMBER TO PORT NAME LOOKUP'''
    def __init__(self):
        
        # Open the MAC Address OUI Dictionary
        with open('ports.pickle', 'rb') as pickleFile:
            self.portDict = pickle.load(pickleFile)
            
    def lookup(self, port, portType):
        try:
            result = self.portDict[(port,portType)]
            return result
        except:
            return "EPH"

if __name__ == '__main__':

        print("PCAP PROCESSOR v 1.0 AUGUST 2021")
        
        # Create Lookup Objects
        macOBJ  = MAC()
        traOBJ  = TRANSPORT()
        portOBJ = PORTS()
        ethOBJ  = ETH()     
        
        ''' Attemp to open a PCAP '''
        while True:
            targetPCAP = input("Target PCAP File: ")
            if not os.path.isfile(targetPCAP):
                print("Invalid File: Please enter valid path\n")
                continue      
            try:
                pcapCapture = open(targetPCAP, 'rb')
                capture = savefile.load_savefile(pcapCapture, layers=0, verbose=False)
                print("PCAP Ready for Processing")
                break
            except:
                # Unable to ingest pcap       
                print("!! Unsupported PCAP File Format !! ")
                continue

        totPackets      = 0
        pktCnt          = 0
        conTbl = PrettyTable(["SRC-IP", "DST-IP", "PROTOCOL", "SRC-MAC", "DST-MAC", "SRC-MFG", "DST-MFG", "SRC-PORT", "SRC-PORT-NAME", "DST-PORT", "DST-PORT-NAME", "TTL", "HR"])
        
        portTbl = PrettyTable(["IP", "PORT", "PORT-DESCRIPTION"])

        ipOBJ = {}        
        portObj = {}        
        # Now process each packet
        for pkt in capture.packets:
            pktCnt += 1

            # extract the hour the packet was captured
            timeStruct  = time.gmtime(pkt.timestamp)
            capHour     = timeStruct.tm_hour - 1     
            
            # Get the raw ethernet frame
            ethFrame = ethernet.Ethernet(pkt.raw())
            
            '''
            Ethernet Header
            0                   1                   2                   3                   4              
            0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7
            +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
            |                                      Destination Address                                      |
            +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
            |                                         Source Address                                        |
            +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
            |           EtherType           |                                                               |
            +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+                                                               +
            |                                                                                               |
            +                                            Payload                                            +
            |                                                                                               |
            +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
        
            '''
                
            ''' ---- Extract the source mac address ---- '''
            srcMAC          = "".join(map(chr, ethFrame.src))
            srcMACLookup    = srcMAC[0:8].upper()
            # remove the colon seperators
            # note the variable names starting with fld, we will use these later
            srcMACLookup  = re.sub(':','',srcMACLookup) 
            
            # Attempt to lookup the mfg in our lookup table 
            # Country Code and Organization
            srcMFG  = macOBJ.lookup(srcMACLookup)    
            
            ''' Extract the destination mac address ---'''
            dstMAC          = "".join(map(chr, ethFrame.dst))
            dstMACLookup    = dstMAC[0:8].upper()
            # remove the colon seperators
            # note the variable names starting with fld, we will use these later
            dstMACLookup  = re.sub(':','',dstMACLookup) 
            
            # Attempt to lookup the mfg in our lookup table 
            # Country Code and Organization
            dstMFG = macOBJ.lookup(dstMACLookup)     
        
            ''' Lookup the Frame Type '''
            frameType = ethOBJ.lookup(ethFrame.type)
            
            '''
            print("====== ETHERNET LAYER =====\n")
            print("TIMESTAMP:", timeStruct)
            print("SRC MAC:  ", srcMAC)
            print("DST MAC:  ", dstMAC)
            print("SRC MFG:  ", srcMFG)
            print("DST MFG:  ", dstMFG)
            print("FRAME TYP:", frameType)
            print("="*40,"\n")
            '''
            
            ''' Process any IPv4 Frames '''
            
            if frameType == "IPv4":
                '''
                ipV4 Header
                0                   1                   2                   3  
                0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
                +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
                |Version|  IHL  |Type of Service|          Total Length         |
                +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
                |         Identification        |Flags|     Fragment Offset     |
                +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
                |  Time to Live |    Protocol   |        Header Checksum        |
                +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
                |                         Source Address                        |
                +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
                |                      Destination Address                      |
                +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
                |                    Options                    |    Padding    |
                +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+   
                '''
                
                ''' Extract the payload '''
                ipPacket = ip.IP(unhexlify(ethFrame.payload))
                ttl = ipPacket.ttl
                    
                ''' Extract the source and destination ip addresses '''
                srcIP = "".join(map(chr,ipPacket.src))
                dstIP = "".join(map(chr,ipPacket.dst))
                
                ''' Extract the protocol in use '''
                protocol = str(ipPacket.p)
                
                ''' Lookup the transport protocol in use '''
                transport = traOBJ.lookup(protocol)[0]
                
                '''
                print("====== IPv4 Transport LAYER =====\n")
                print("TTL:   ",   ttl)
                print("SRC-IP:",   srcIP)
                print("DST-IP:",   dstIP)
                print("Protocol:", protocol)
                print("="*40,"\n")
                '''
                
                if transport == "TCP":
                    
                    '''
                    TCP HEADER
                    0                   1                   2                   3  
                    0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
                    +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
                    |          Source Port          |        Destination Port       |
                    +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
                    |                        Sequence Number                        |
                    +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
                    |                     Acknowledgment Number                     |
                    +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
                    | Offset|  Res. |     Flags     |             Window            |
                    +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
                    |            Checksum           |         Urgent Pointer        |
                    +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
                    |                    Options                    |    Padding    |
                    +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
                    '''
                    
                    ''' 
                    **** YOUR CODE HERE *******************************************************************************************************************************************************
                
                    '''
                    
                    tcpPacket = tcp.TCP(unhexlify(ipPacket.payload))
                    
                    srcPort = tcpPacket.src_port
                    dstPort = tcpPacket.dst_port
                    
                    srcPortDesc = portOBJ.lookup(str(srcPort), "TCP")
                    if srcPortDesc == "EPH":
                        srcPort = "EPH"
                    else:
                        srcPort = str(srcPort)
                        
                    dstPortDesc = portOBJ.lookup(str(dstPort), "TCP")
                    if dstPortDesc == "EPH":
                        dstPort = "EPH"
                    else:
                        dstPort = str(dstPort)
                        
                    key = (srcMAC, dstMAC, srcPort, dstPort, "TCP")
                    value = (srcIP, dstIP, srcPortDesc, dstPortDesc, srcMFG, dstMFG, ttl, capHour)
                       
                    ipOBJ[key] = value
                    
                    srcPortKey = (srcIP, srcPort)
                    srcPortValue = srcPortDesc
                    
                    dstPortKey = (dstIP, dstPort)
                    dstPortValue = dstPortDesc                   
                    
                    portObj[srcPortKey] = srcPortValue
                    portObj[dstPortKey] = dstPortValue
                    
                    '''
                     value = [srcIP, dstIP, srcPortDesc, dstPortDesc, srcMFG, dstMFG, ttl]
                        
                    ipOBJ.AddOb(key, value, capHour)
                    
                    '''
                     
                elif transport == "UDP":
                    '''
                     0                   1                   2                   3  
                     0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
                     +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
                     |          Source Port          |        Destination Port       |
                     +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
                     |             Length            |            Checksum           |
                     +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
                     '''
                    
                    ''' 
                    **** YOUR CODE HERE ********************************************************************************************************************************************************
                
                    '''    
                    udpPacket = udp.UDP(unhexlify(ipPacket.payload))
                    
                    srcPort = udpPacket.src_port
                    dstPort = udpPacket.dst_port
                    
                    srcPortDesc = portOBJ.lookup(str(srcPort), "UDP")
                    if srcPortDesc == "EPH":
                        srcPort = "EPH"
                    else:
                        srcPort = str(srcPort)
                        
                    dstPortDesc = portOBJ.lookup(str(dstPort), "UDP")
                    if dstPortDesc == "EPH":
                        dstPort = "EPH"
                    else:
                        dstPort = str(dstPort)
                        
                    key = (srcMAC, dstMAC, srcPort, dstPort, "UDP")
                    value = (srcIP, dstIP, srcPortDesc, dstPortDesc, srcMFG, dstMFG, ttl, capHour)
                       
                    ipOBJ[key] = value
                    
                    srcPortKey = (srcIP, srcPort)
                    srcPortValue = srcPortDesc
                    
                    dstPortKey = (dstIP, dstPort)
                    dstPortValue = dstPortDesc                   
                    
                    portObj[srcPortKey] = srcPortValue
                    portObj[dstPortKey] = dstPortValue                    
                  
                elif transport == "ICMP":
                    '''
                     0                   1                   2                   3  
                     0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
                     +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
                     |      Type     |      Code     |            Checksum           |
                     +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
                     |                                                               |
                     +                          Message Body                         +
                     |                                                               |
                     +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
                     '''
                    ''' 
                    **** YOUR CODE HERE ********************************************************************************************************************************************************
                
                    '''            
                    key = (srcMAC, dstMAC, "", "", "ICMP")
                    value = (srcIP, dstIP, "", "", srcMFG, dstMFG, "", "")
                       
                    ipOBJ[key] = value
                    
            elif frameType == "ARP":
                '''
                0                   1      
                0 1 2 3 4 5 6 7 8 9 0 1 2 3
                +-+-+-+-+-+-+-+-+-+-+-+-+-+-+
                |  Dst-MAC  |  Src-MAC  |TYP|
                +-+-+-+-+-+-+-+-+-+-+-+-+-+-+
                |                           |
                +       Request-Reply       +
                |                           |
                +-+-+-+-+-+-+-+-+-+-+-+-+-+-+
                |        PAD        |  CRC  |
                +-+-+-+-+-+-+-+-+-+-+-+-+-+-+
                '''
                
                ''' 
                **** YOUR CODE HERE ********************************************************************************************************************************************************
            
                '''                
                 
                key = (srcMAC, dstMAC, "", "", "ARP")
                value = ("", "", "", "", srcMFG, dstMFG, "", "")
                   
                ipOBJ[key] = value  
            
            else:
                continue
        '''    
        conTbl.field_names["SRC-IP", "DST-IP", "PROTOCOL", "SRC-MAC", "DST-MAC", "SRC-MFG", "DST-MFG", "SRC-PORT", "SRC-PORT-NAME", "DST-PORT", "DST-PORT-NAME", "TTL", "HR"]
        key = (srcMAC, dstMAC, srcPort, dstPort, "TCP")
        value = [srcIP, dstIP, srcPortDesc, dstPortDesc, srcMFG, dstMFG, ttl, capHour]
        
        
        portTbl.field_names["IP", "PORT", "PORT-DESCRIPTION"]
        srcPortKey = (srcIP, srcPort)
        srcPortValue = [srcPortDesc]
        '''
        
        for key, value in ipOBJ.items():
            conTbl.add_row([value[0], value[1], key[4], key[0], key[1], value[4], value[5], key[2], value[2], key[3], value[3], value[6], value[7]])
            
        for key, value in portObj.items():
            portTbl.add_row([key[0], key[1], value])
            
        conTbl.sortby = "PROTOCOL"
        conTbl.reversesort = False        
        print(conTbl)
        
        portTbl.sortby = "IP"
        portTbl.reversesort = True        
        print(portTbl)        
            
        print("\n\nScript End")
